spring.application.name=duotec
# Define o link de acesso ao banco em memória
spring.datasource.url=jdbc:h2:mem:duotecdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa a interface visual do banco para podermos olhar as tabelas pelo navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Faz o Spring mostrar os comandos SQL automáticos no terminal (bom para aprender!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update