spring.application.name=duotec
# Alterar para a porta padrão do MySQL e o nome do seu banco (ex: duotec)
spring.datasource.url=jdbc:mysql://localhost:3306/duotec?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Capamba@24
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ddl-auto: 'update' atualiza a estrutura existente sem apagar os dados dos seus usuários
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect